<?php

namespace backend\models;

use Yii;

/**
 * This is the model class for table "paket".
 *
 * @property int $id_paket
 * @property string $tanggal_paket
 * @property string $jenis_paket
 * @property int $tujuan_paket
 * @property string $pengirim_paket
 * @property string $status_paket
 * @property int $penerima_paket
 *
 * @property User $tujuanPaket
 * @property User $penerimaPaket
 */
class Paket extends \yii\db\ActiveRecord
{
    /**
     * {@inheritdoc}
     */
    public static function tableName()
    {
        return 'paket';
    }

    /**
     * {@inheritdoc}
     */
    public function rules()
    {
        return [
            [['tanggal_paket'], 'safe'],
            [['tujuan_paket', 'penerima_paket'], 'integer'],
            [['jenis_paket'], 'string', 'max' => 16],
            [['pengirim_paket'], 'string', 'max' => 50],
            [['status_paket'], 'string', 'max' => 1],
            [['tujuan_paket'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['tujuan_paket' => 'id']],
            [['penerima_paket'], 'exist', 'skipOnError' => true, 'targetClass' => User::className(), 'targetAttribute' => ['penerima_paket' => 'id']],
        ];
    }

    /**
     * {@inheritdoc}
     */
    public function attributeLabels()
    {
        return [
            'id_paket' => 'Id Paket',
            'tanggal_paket' => 'Tanggal Paket',
            'jenis_paket' => 'Jenis Paket',
            'tujuan_paket' => 'Tujuan Paket',
            'pengirim_paket' => 'Pengirim Paket',
            'status_paket' => 'Status Paket',
            'penerima_paket' => 'Penerima Paket',
        ];
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getTujuanPaket()
    {
        return $this->hasOne(User::className(), ['id' => 'tujuan_paket']);
    }

    /**
     * @return \yii\db\ActiveQuery
     */
    public function getPenerimaPaket()
    {
        return $this->hasOne(User::className(), ['id' => 'penerima_paket']);
    }

    public function beforeSave($insert)
    {
        Yii::error('tanggal1: '.$this->tanggal_paket);
        $this->tanggal_paket = Yii::$app->formatter->asDatetime(strtotime($this->tanggal_paket), 'Y-M-d h:m:s');
        Yii::error('tanggal2: '.$this->tanggal_paket);
        return parent::beforeSave($insert); // TODO: Change the autogenerated stub
    }


}
